# This configuration file contains all options for the vulkan-renderer.
# Do not change any values unless you know exactly what you are doing!

title = "Inexor vulkan-renderer"

#TODO: Declare further TOML configuration files here?

[application]
name = "Inexor-Application"

[application.engine]
name = "Inexor-Engine"

[application.window]
mode = "windowed"
width = 1280
height = 900
name = "Inexor vulkan-renderer"
