#include "inexor/vulkan-renderer/render-modules/imgui_renderer.hpp"

#include "inexor/vulkan-renderer/wrapper/descriptors/descriptor_set_allocator.hpp"
#include "inexor/vulkan-renderer/wrapper/descriptors/descriptor_set_layout_builder.hpp"
#include "inexor/vulkan-renderer/wrapper/descriptors/write_descriptor_set_builder.hpp"
#include "inexor/vulkan-renderer/wrapper/exception.hpp"

#include <stdexcept>
#include <utility>

namespace inexor::vulkan_renderer::render_modules {

// Using declarations
using wrapper::InexorException;
using wrapper::descriptors::DescriptorSetAllocator;
using wrapper::descriptors::DescriptorSetLayoutBuilder;
using wrapper::descriptors::WriteDescriptorSetBuilder;

ImGuiRenderer::ImGuiRenderer(const Device &device,
                             std::weak_ptr<GraphicsPass> previous_pass,
                             std::weak_ptr<Swapchain> swapchain,
                             std::function<void()> on_update_user_imgui_data)
    : RenderModuleBase(device, "ImGuiRenderer"), m_on_update_user_imgui_data(std::move(on_update_user_imgui_data)),
      m_previous_pass(std::move(previous_pass)), m_swapchain(std::move(swapchain)) {

    if (m_swapchain.expired()) {
        throw InexorException("Error: Parameter 'swapchain' is an invalid pointer!");
    }
    // NOTE: It's valid for previous_pass to be an invalid pointer (in that case there is no previous pass!)

    spdlog::trace("Creating ImGui context");
    m_imgui_context = ImGui::CreateContext();
    ImGui::SetCurrentContext(m_imgui_context);

    spdlog::trace("Loading ImGui font texture");
    load_font_data_from_file();

    spdlog::trace("Setting ImGui style");
    set_imgui_style();
}

ImGuiRenderer::~ImGuiRenderer() {
    ImGui::DestroyContext(m_imgui_context);
    m_imgui_context = nullptr;
}

void ImGuiRenderer::setup_buffers() {}

void ImGuiRenderer::setup_textures() {}

void ImGuiRenderer::setup_graphics_passes(GraphicsPassBuilder &builder) {
    m_graphics_passes.emplace_back(builder.writes_to(m_swapchain)
                                       .conditionally_reads_from(m_previous_pass, !m_previous_pass.expired())
                                       .build("ImGui", render_graph::DebugLabelColor::BLUE));
}

void ImGuiRenderer::setup_graphics_pipelines(GraphicsPipelineBuilder &builder) {}

void ImGuiRenderer::setup_shaders() {
    m_shaders.emplace_back(m_device, "ImGui|vert", VK_SHADER_STAGE_VERTEX_BIT, "shaders/ui.vert.spv");
    m_shaders.emplace_back(m_device, "ImGui|frag", VK_SHADER_STAGE_FRAGMENT_BIT, "shaders/ui.frag.spv");
}

void ImGuiRenderer::setup_descriptor_set_layouts(DescriptorSetLayoutBuilder &builder) {
    m_descriptor_set_layouts.emplace_back(
        builder.add(wrapper::descriptors::DescriptorType::COMBINED_IMAGE_SAMPLER, VK_SHADER_STAGE_FRAGMENT_BIT)
            .build("ImGui|Texture"));
}

void ImGuiRenderer::allocate_descriptor_sets(DescriptorSetAllocator &allocator) {
    m_descriptor_set = allocator.allocate("ImGui|Texture", m_descriptor_set_layouts[0]);
}

void ImGuiRenderer::update_descriptor_sets(WriteDescriptorSetBuilder &builder) {
    builder.add(m_descriptor_set, m_imgui_texture);
}

void ImGuiRenderer::update_buffers() {
    m_on_update_user_imgui_data();
    const ImDrawData *draw_data = ImGui::GetDrawData();

    m_index_data.clear();
    m_vertex_data.clear();
    // We need to collect the vertices and indices generated by ImGui
    // because it does not store them in one array, but rather in chunks (command lists)
    for (std::size_t i = 0; i < draw_data->CmdListsCount; i++) {
        const ImDrawList *cmd_list = draw_data->CmdLists[i]; // NOLINT
        for (std::size_t j = 0; j < cmd_list->IdxBuffer.Size; j++) {
            m_index_data.push_back(cmd_list->IdxBuffer.Data[j]); // NOLINT
        }
        for (std::size_t j = 0; j < cmd_list->VtxBuffer.Size; j++) {
            m_vertex_data.push_back(cmd_list->VtxBuffer.Data[j]); // NOLINT
        }
    }
    if (m_vertex_data.size() > 0) {
        m_vertex_buffer->request_update(m_vertex_data);
    }
    if (m_index_data.size() > 0) {
        m_index_buffer->request_update(m_index_data);
    }
}

void ImGuiRenderer::update_textures() {
    // ImGuiRenderer does not need to update any textures because the texture that is loaded at startup doesn't change
    // NOTE: We are still forced to explicitely implement update_textures() when inheriting from RenderModuleBase
}

void ImGuiRenderer::setup_buffers() {
    m_vertex_buffer = std::make_shared<BufferResource>("ImGui|Vertex", BufferType::VERTEX_BUFFER);
    m_buffers.push_back(m_vertex_buffer);
    m_index_buffer = std::make_shared<BufferResource>("ImGui|Index", BufferType::INDEX_BUFFER);
    m_buffers.push_back(m_index_buffer);
}

void ImGuiRenderer::load_font_data_from_file() {
    ImGuiIO &io = ImGui::GetIO();
    io.FontGlobalScale = 1.0f;

    // This is here because it doesn't need to be member data
    constexpr const char *FONT_FILE_PATH = "assets/fonts/NotoSans-Bold.ttf";
    constexpr float FONT_SIZE = 18.0f;

    spdlog::trace("Loading front {} with size {}", FONT_FILE_PATH, FONT_SIZE);
    ImFont *font = io.Fonts->AddFontFromFileTTF(FONT_FILE_PATH, FONT_SIZE);
    io.Fonts->GetTexDataAsRGBA32(&m_font_texture_data, &m_font_texture_width, &m_font_texture_height);

    constexpr int FONT_TEXTURE_CHANNELS = 4;
    m_font_texture_data_size = m_font_texture_width * m_font_texture_height * FONT_TEXTURE_CHANNELS;
}

void ImGuiRenderer::set_imgui_style() {
    ImGuiStyle &style = ImGui::GetStyle();
    style.Colors[ImGuiCol_TitleBg] = {1.0f, 0.0f, 0.0f, 1.0f};
    style.Colors[ImGuiCol_TitleBgActive] = {1.0f, 0.0f, 0.0f, 1.0f};
    style.Colors[ImGuiCol_TitleBgCollapsed] = {1.0f, 0.0f, 0.0f, 0.1f};
    style.Colors[ImGuiCol_MenuBarBg] = {1.0f, 0.0f, 0.0f, 0.4f};
    style.Colors[ImGuiCol_Header] = {0.8f, 0.0f, 0.0f, 0.4f};
    style.Colors[ImGuiCol_HeaderActive] = {1.0f, 0.0f, 0.0f, 0.4f};
    style.Colors[ImGuiCol_HeaderHovered] = {1.0f, 0.0f, 0.0f, 0.4f};
    style.Colors[ImGuiCol_FrameBg] = {0.0f, 0.0f, 0.0f, 0.8f};
    style.Colors[ImGuiCol_CheckMark] = {1.0f, 0.0f, 0.0f, 0.8f};
    style.Colors[ImGuiCol_SliderGrab] = {1.0f, 0.0f, 0.0f, 0.4f};
    style.Colors[ImGuiCol_SliderGrabActive] = {1.0f, 0.0f, 0.0f, 0.8f};
    style.Colors[ImGuiCol_FrameBgHovered] = {1.0f, 1.0f, 1.0f, 0.1f};
    style.Colors[ImGuiCol_FrameBgActive] = {1.0f, 1.0f, 1.0f, 0.2f};
    style.Colors[ImGuiCol_Button] = {1.0f, 0.0f, 0.0f, 0.4f};
    style.Colors[ImGuiCol_ButtonHovered] = {1.0f, 0.0f, 0.0f, 0.6f};
    style.Colors[ImGuiCol_ButtonActive] = {1.0f, 0.0f, 0.0f, 0.8f};
}

void ImGuiRenderer::record_command_buffer(const CommandBuffer &cmd_buf) {
    // TODO: There is better way to handle ImGui with Vulkan, read the ImGui docs!

    ImDrawData *draw_data = ImGui::GetDrawData();
    if (draw_data == nullptr || draw_data->TotalIdxCount == 0 || draw_data->TotalVtxCount == 0) {
        m_on_update_user_imgui_data();
        return;
    }
    const ImGuiIO &io = ImGui::GetIO();
    m_push_const_block.scale = glm::vec2(2.0f / io.DisplaySize.x, 2.0f / io.DisplaySize.y);

    cmd_buf.bind_pipeline(m_graphics_pipelines[0])
        .bind_descriptor_set(m_descriptor_set, m_graphics_pipelines[0])
        .push_constant(m_graphics_pipelines[0], m_push_const_block, VK_SHADER_STAGE_VERTEX_BIT)
        .bind_vertex_buffer(m_vertex_buffer)
        .bind_index_buffer(m_index_buffer)
        .set_viewport({
            .width = ImGui::GetIO().DisplaySize.x,
            .height = ImGui::GetIO().DisplaySize.y,
            .minDepth = 0.0f,
            .maxDepth = 1.0f,
        });

    std::uint32_t index_offset = 0;
    std::int32_t vertex_offset = 0;
    for (std::size_t i = 0; i < draw_data->CmdListsCount; i++) {
        const ImDrawList *cmd_list = draw_data->CmdLists[i];
        for (std::int32_t j = 0; j < cmd_list->CmdBuffer.Size; j++) {
            const ImDrawCmd &draw_cmd = cmd_list->CmdBuffer[j];
            cmd_buf.set_scissor({
                .offset{
                    .x = std::max(static_cast<int32_t>(draw_cmd.ClipRect.x), 0),
                    .y = std::max(static_cast<int32_t>(draw_cmd.ClipRect.y), 0),
                },
                .extent{
                    .width = static_cast<uint32_t>(draw_cmd.ClipRect.z - draw_cmd.ClipRect.x),
                    .height = static_cast<uint32_t>(draw_cmd.ClipRect.w - draw_cmd.ClipRect.y),
                },
            });
            cmd_buf.draw_indexed(draw_cmd.ElemCount, 1, index_offset, vertex_offset);
            index_offset += draw_cmd.ElemCount;
        }
        vertex_offset += cmd_list->VtxBuffer.Size;
    }
}

} // namespace inexor::vulkan_renderer::render_modules
