#include "inexor/vulkan-renderer/rendering/imgui/imgui_renderer.hpp"

#include <stdexcept>
#include <utility>

namespace inexor::vulkan_renderer::rendering::imgui {

ImGuiRenderer::ImGuiRenderer(std::weak_ptr<RenderGraph> rendergraph,
                             std::weak_ptr<GraphicsPass> previous_pass,
                             std::weak_ptr<Swapchain> swapchain,
                             std::function<void()> on_update_user_imgui_data)
    : m_on_update_user_imgui_data(std::move(on_update_user_imgui_data)), m_previous_pass(std::move(previous_pass)),
      m_swapchain(std::move(swapchain)) {
    if (rendergraph.expired()) {
        throw std::invalid_argument(
            "[ImGuiRenderer::ImGuiRenderer] Error: Parameter 'rendergraph' is not a valid pointer!");
    }
    if (m_swapchain.expired()) {
        throw std::invalid_argument(
            "[ImGuiRenderer::ImGuiRenderer] Error: Parameter 'swapchain' is not a valid pointer!");
    }
    // NOTE: It's valid for previous_pass to be an invalid pointer (in that case there is no previous pass!)

    spdlog::trace("Creating ImGui context");
    m_imgui_context = ImGui::CreateContext();
    ImGui::SetCurrentContext(m_imgui_context);

    spdlog::trace("Loading ImGui font texture");
    load_font_data_from_file();

    spdlog::trace("Setting ImGui style");
    set_imgui_style();

    auto rg = rendergraph.lock();

    m_vertex_shader =
        std::make_shared<Shader>(rg->device(), "ImGui", VK_SHADER_STAGE_VERTEX_BIT, "shaders/ui.vert.spv");
    m_fragment_shader =
        std::make_shared<Shader>(rg->device(), "ImGui", VK_SHADER_STAGE_FRAGMENT_BIT, "shaders/ui.frag.spv");

    m_vertex_buffer = rg->add_buffer("ImGui|Vertex", BufferType::VERTEX_BUFFER, [&]() {
        m_on_update_user_imgui_data();
        const ImDrawData *draw_data = ImGui::GetDrawData();

        m_index_data.clear();
        m_vertex_data.clear();
        // We need to collect the vertices and indices generated by ImGui
        // because it does not store them in one array, but rather in chunks (command lists)
        for (std::size_t i = 0; i < draw_data->CmdListsCount; i++) {
            const ImDrawList *cmd_list = draw_data->CmdLists[i]; // NOLINT
            for (std::size_t j = 0; j < cmd_list->IdxBuffer.Size; j++) {
                m_index_data.push_back(cmd_list->IdxBuffer.Data[j]); // NOLINT
            }
            for (std::size_t j = 0; j < cmd_list->VtxBuffer.Size; j++) {
                m_vertex_data.push_back(cmd_list->VtxBuffer.Data[j]); // NOLINT
            }
        }
        if (m_vertex_data.size() > 0) {
            m_vertex_buffer.lock()->request_update(m_vertex_data);
        }
    });

    m_index_buffer = rg->add_buffer("ImGui|Index", BufferType::INDEX_BUFFER, [&]() {
        if (m_index_data.size() > 0) {
            m_index_buffer.lock()->request_update(m_index_data);
        }
    });

    // Setupt the ImGui font texture
    m_imgui_texture =
        rg->add_texture("ImGui-Font", TextureUsage::DEFAULT, VK_FORMAT_R8G8B8A8_UNORM, m_font_texture_width,
                        m_font_texture_height, 4, VK_SAMPLE_COUNT_1_BIT, [&]() {
                            // Initialize the ImGui font texture only once in the update function
                            if (!m_font_texture_initialized) {
                                m_imgui_texture.lock()->request_update(m_font_texture_data, m_font_texture_data_size);
                                m_font_texture_initialized = true;
                            }
                        });

    // Setup the ImGui graphics pipeline
    rg->add_graphics_pipeline([&](GraphicsPipelineBuilder &builder) {
        m_imgui_pipeline =
            builder
                .set_vertex_input_bindings({
                    {
                        .binding = 0,
                        .stride = sizeof(ImDrawVert),
                        .inputRate = VK_VERTEX_INPUT_RATE_VERTEX,
                    },
                })
                .set_vertex_input_attributes({
                    {
                        .location = 0,
                        .format = VK_FORMAT_R32G32_SFLOAT,
                        .offset = offsetof(ImDrawVert, pos),
                    },
                    {
                        .location = 1,
                        .format = VK_FORMAT_R32G32_SFLOAT,
                        .offset = offsetof(ImDrawVert, uv),
                    },
                    {
                        .location = 2,
                        .format = VK_FORMAT_R8G8B8A8_UNORM,
                        .offset = offsetof(ImDrawVert, col),
                    },
                })
                .add_default_color_blend_attachment()
                .add_color_attachment_format(m_swapchain.lock()->image_format())
                .set_dynamic_states({
                    VK_DYNAMIC_STATE_VIEWPORT,
                    VK_DYNAMIC_STATE_SCISSOR,
                })
                // NOTE: Even thoguh viewport and scissor are dynamic states, we still need to specify 1 for each
                .set_scissor(m_swapchain.lock()->extent())
                .set_viewport(m_swapchain.lock()->extent())
                .add_shader(m_vertex_shader)
                .add_shader(m_fragment_shader)
                .set_descriptor_set_layout(m_descriptor_set_layout)
                .add_push_constant_range(VK_SHADER_STAGE_VERTEX_BIT, sizeof(m_push_const_block))
                .build("ImGui");
        return m_imgui_pipeline;
    });

    // Setup the ImGui graphics pass
    m_imgui_pass = rg->add_graphics_pass(
        rg->get_graphics_pass_builder()
            .writes_to(m_swapchain)
            .conditionally_reads_from(m_previous_pass, !m_previous_pass.expired())
            .set_on_record([&](const wrapper::commands::CommandBuffer &cmd_buf) {
                ImDrawData *draw_data = ImGui::GetDrawData();
                if (draw_data == nullptr || draw_data->TotalIdxCount == 0 || draw_data->TotalVtxCount == 0) {
                    m_on_update_user_imgui_data();
                    return;
                }
                const ImGuiIO &io = ImGui::GetIO();
                m_push_const_block.scale = glm::vec2(2.0f / io.DisplaySize.x, 2.0f / io.DisplaySize.y);

                cmd_buf.bind_pipeline(m_imgui_pipeline)
                    .bind_descriptor_set(m_descriptor_set, m_imgui_pipeline)
                    .push_constant(m_imgui_pipeline, m_push_const_block, VK_SHADER_STAGE_VERTEX_BIT)
                    .bind_vertex_buffer(m_vertex_buffer)
                    .bind_index_buffer(m_index_buffer)
                    .set_viewport(VkViewport{.width = ImGui::GetIO().DisplaySize.x,
                                             .height = ImGui::GetIO().DisplaySize.y,
                                             .minDepth = 0.0f,
                                             .maxDepth = 1.0f});

                std::uint32_t index_offset = 0;
                std::int32_t vertex_offset = 0;
                for (std::size_t i = 0; i < draw_data->CmdListsCount; i++) {
                    const ImDrawList *cmd_list = draw_data->CmdLists[i];
                    for (std::int32_t j = 0; j < cmd_list->CmdBuffer.Size; j++) {
                        const ImDrawCmd &draw_cmd = cmd_list->CmdBuffer[j];
                        VkRect2D scissor{};
                        scissor.offset.x = std::max((int32_t)(draw_cmd.ClipRect.x), 0);
                        scissor.offset.y = std::max((int32_t)(draw_cmd.ClipRect.y), 0);
                        scissor.extent.width = (uint32_t)(draw_cmd.ClipRect.z - draw_cmd.ClipRect.x);
                        scissor.extent.height = (uint32_t)(draw_cmd.ClipRect.w - draw_cmd.ClipRect.y);
                        cmd_buf.set_scissor(scissor);
                        cmd_buf.draw_indexed(draw_cmd.ElemCount, 1, index_offset, vertex_offset);
                        index_offset += draw_cmd.ElemCount;
                    }
                    vertex_offset += cmd_list->VtxBuffer.Size;
                }
            })
            .build("ImGui", render_graph::DebugLabelColor::BLUE));
}

ImGuiRenderer::~ImGuiRenderer() {
    ImGui::DestroyContext(m_imgui_context);
    m_imgui_context = nullptr;
}

void ImGuiRenderer::load_font_data_from_file() {
    ImGuiIO &io = ImGui::GetIO();
    io.FontGlobalScale = 1.0f;

    // This is here because it doesn't need to be member data
    constexpr const char *FONT_FILE_PATH = "assets/fonts/NotoSans-Bold.ttf";
    constexpr float FONT_SIZE = 18.0f;

    spdlog::trace("Loading front {} with size {}", FONT_FILE_PATH, FONT_SIZE);
    ImFont *font = io.Fonts->AddFontFromFileTTF(FONT_FILE_PATH, FONT_SIZE);
    io.Fonts->GetTexDataAsRGBA32(&m_font_texture_data, &m_font_texture_width, &m_font_texture_height);

    constexpr int FONT_TEXTURE_CHANNELS = 4;
    m_font_texture_data_size = m_font_texture_width * m_font_texture_height * FONT_TEXTURE_CHANNELS;
}

void ImGuiRenderer::set_imgui_style() {
    ImGuiStyle &style = ImGui::GetStyle();
    style.Colors[ImGuiCol_TitleBg] = ImVec4(1.0f, 0.0f, 0.0f, 1.0f);
    style.Colors[ImGuiCol_TitleBgActive] = ImVec4(1.0f, 0.0f, 0.0f, 1.0f);
    style.Colors[ImGuiCol_TitleBgCollapsed] = ImVec4(1.0f, 0.0f, 0.0f, 0.1f);
    style.Colors[ImGuiCol_MenuBarBg] = ImVec4(1.0f, 0.0f, 0.0f, 0.4f);
    style.Colors[ImGuiCol_Header] = ImVec4(0.8f, 0.0f, 0.0f, 0.4f);
    style.Colors[ImGuiCol_HeaderActive] = ImVec4(1.0f, 0.0f, 0.0f, 0.4f);
    style.Colors[ImGuiCol_HeaderHovered] = ImVec4(1.0f, 0.0f, 0.0f, 0.4f);
    style.Colors[ImGuiCol_FrameBg] = ImVec4(0.0f, 0.0f, 0.0f, 0.8f);
    style.Colors[ImGuiCol_CheckMark] = ImVec4(1.0f, 0.0f, 0.0f, 0.8f);
    style.Colors[ImGuiCol_SliderGrab] = ImVec4(1.0f, 0.0f, 0.0f, 0.4f);
    style.Colors[ImGuiCol_SliderGrabActive] = ImVec4(1.0f, 0.0f, 0.0f, 0.8f);
    style.Colors[ImGuiCol_FrameBgHovered] = ImVec4(1.0f, 1.0f, 1.0f, 0.1f);
    style.Colors[ImGuiCol_FrameBgActive] = ImVec4(1.0f, 1.0f, 1.0f, 0.2f);
    style.Colors[ImGuiCol_Button] = ImVec4(1.0f, 0.0f, 0.0f, 0.4f);
    style.Colors[ImGuiCol_ButtonHovered] = ImVec4(1.0f, 0.0f, 0.0f, 0.6f);
    style.Colors[ImGuiCol_ButtonActive] = ImVec4(1.0f, 0.0f, 0.0f, 0.8f);
}

} // namespace inexor::vulkan_renderer::rendering::imgui
