#pragma once

#include "inexor/vulkan-renderer/rendering/render-graph/render_graph.hpp"

#include "inexor/vulkan-renderer/rendering/render-graph/buffer.hpp"
#include "inexor/vulkan-renderer/rendering/render-graph/graphics_pass.hpp"
#include "inexor/vulkan-renderer/rendering/render-graph/texture.hpp"
#include "inexor/vulkan-renderer/wrapper/pipelines/pipeline.hpp"
#include "inexor/vulkan-renderer/wrapper/pipelines/pipeline_builder.hpp"
#include "inexor/vulkan-renderer/wrapper/swapchain.hpp"

#include <glm/vec2.hpp>
#include <imgui.h>

#include <memory>

namespace inexor::vulkan_renderer::rendering::imgui {

// Using declarations
using render_graph::Buffer;
using render_graph::BufferType;
using render_graph::RenderGraph;
using render_graph::Texture;
using render_graph::TextureUsage;
using wrapper::GraphicsPass;
using wrapper::Shader;
using wrapper::Swapchain;
using wrapper::pipelines::GraphicsPipeline;
using wrapper::pipelines::GraphicsPipelineBuilder;

/// A rendering class for ImGui
class ImGuiRenderer {
private:
    /// The ImGui context
    ImGuiContext *m_imgui_context{nullptr};
    /// A pointer to the font texture data
    unsigned char *m_font_texture_data{nullptr};
    /// The size of the font texture data in bytes
    int m_font_texture_data_size{0};
    /// The width of the ImGui font texture
    int m_font_texture_width{0};
    /// The height of the ImGui font texture
    int m_font_texture_height{0};
    // Set to ``true`` once the ImGui font texture is initialized
    bool m_font_texture_initialized{false};

    std::shared_ptr<Shader> m_vertex_shader;
    std::shared_ptr<Shader> m_fragment_shader;
    std::weak_ptr<Buffer> m_index_buffer;
    std::weak_ptr<Buffer> m_vertex_buffer;
    std::weak_ptr<Texture> m_imgui_texture;
    std::shared_ptr<GraphicsPipeline> m_imgui_pipeline;
    std::weak_ptr<GraphicsPass> m_imgui_pass;
    // This swapchain is the color attachment we will write to
    std::weak_ptr<Swapchain> m_swapchain;
    // This is the previous pass we read from
    std::weak_ptr<GraphicsPass> m_previous_pass;
    // The user-defined update of ImGui data
    std::function<void()> m_on_update_user_imgui_data;

    // We need to collect the vertices and indices generated by ImGui
    // because it does not store them in one array, but rather in chunks
    std::vector<ImDrawVert> m_vertex_data;
    std::vector<std::uint32_t> m_index_data;

    VkDescriptorSetLayout m_descriptor_set_layout{VK_NULL_HANDLE};
    VkDescriptorSet m_descriptor_set{VK_NULL_HANDLE};

    /// ImGui push constant block
    /// Note that neither scale nor translation change
    struct PushConstBlock {
        glm::vec2 scale{-1.0f};
        glm::vec2 translate{-1.0f};
    } m_push_const_block;

    /// Load the font data to fill the font texture with
    void load_font_data_from_file();

    /// Customize ImGui style like text color for example
    void set_imgui_style();

public:
    /// Default constructor
    /// @param rendergraph
    /// @param previous_pass
    /// @param swapchain
    /// @param on_update_user_imgui_data
    ImGuiRenderer(std::weak_ptr<RenderGraph> rendergraph,
                  std::weak_ptr<GraphicsPass> previous_pass,
                  std::weak_ptr<Swapchain> swapchain,
                  std::function<void()> on_update_user_imgui_data);

    ~ImGuiRenderer();
};

} // namespace inexor::vulkan_renderer::rendering::imgui
