name: Commit Naming
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  naming:
    name: Commit Naming
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.merged }}
    steps:
      - uses: IceflowRE/gitcc@v2
        with:
          validator_file: .github/helper/commit_validator.mjs
