name: Commit Naming
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  naming:
    name: Commit Naming
    runs-on: ubuntu-slim
    if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.merged }}
    steps:
      - uses: IceflowRE/gitcc@v3
        with:
          validator: "regex"
          options: |
            summary: "^[A-Z0-9]\S*(?:\s\S*)+[^.!?,\s]$"
