name: GHA
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  code-style:
    name: Code Style
    uses: ./.github/workflows/code_style.yml

  linux-build:
    name: Linux
    uses: ./.github/workflows/linux_builds.yml
    with:
      vulkan-sdk-version: "1.4.357.0"
      vulkan-sdk-checksum: "0f09bf6a0625e346bf004be70b92907e934a4c76606b323441b2baf3a5a0e66d"

  windows-build:
    name: Windows
    uses: ./.github/workflows/windows_builds.yml
    with:
      vulkan-sdk-version: "1.4.357.0"
      vulkan-sdk-checksum: "81f474711e9042f4cd22b31b2f7a8870db2e428b21586fb43dd80150be97310d"

  documentation:
    name: Documentation
    uses: ./.github/workflows/documentation.yml
    with:
      vulkan-sdk-version: "1.4.357.0"
      vulkan-sdk-checksum: "0f09bf6a0625e346bf004be70b92907e934a4c76606b323441b2baf3a5a0e66d"

  static-analysis:
    name: Static Analysis
    needs:
      - linux-build
      - windows-build
    uses: ./.github/workflows/static_analysis.yml
    with:
      vulkan-sdk-version: "1.4.357.0"
      vulkan-sdk-checksum-linux: "0f09bf6a0625e346bf004be70b92907e934a4c76606b323441b2baf3a5a0e66d"
      vulkan-sdk-checksum-windows: "81f474711e9042f4cd22b31b2f7a8870db2e428b21586fb43dd80150be97310d"

  release:
    name: Release
    needs:
      - linux-build
      - windows-build
      - documentation
    uses: ./.github/workflows/release.yml
